# adapted from https://github.com/PHPirates/travis-ci-latex-pdf#instructions-for-building-with-tex-live-from-a-docker-image

sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/Strauman/travis-latexbuild/tree/master#configuration-options
tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=main.tex
- latexmk-flags=-pdf
# Check at https://www.ctan.org/pkg/package-name in which TeX Live package a LaTeX package is contained.
- packages=babel, babel-french, inputenc, fontenc, geometry, amsmath, graphicx, hyperref, lm, url, color, xcolor, listings, amsmath, amsfonts, amssymb, amsthm, multicol

# We will use the docker image from https://hub.docker.com/r/strauman/travis-latexbuild/
script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small
